// import { ReactQueryClientProvider } from "@/components/others/query-client-provider";
import { ThemeProvider } from "@/components/theme-provider";
// import { Toaster } from "@/components/ui/toaster";
// import { PublicEnvScript } from "next-runtime-env";

import { Inter } from "next/font/google";
import "./globals.css";
import ToggleTheme from "@/components/toggle-theme";

const inter = Inter({ subsets: ["latin"], weight: ["400"], display: "swap" });

export const metadata = {
  title: "NetAi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <ReactQueryClientProvider>
    <html lang="en" suppressHydrationWarning>
      <head>{/* <PublicEnvScript /> */}</head>
      <body className={`${inter.className} tracking-tighter px-16 py-8`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed top-4 right-10 z-50">
            <ToggleTheme />
          </div>
          {children}
          {/* <Toaster /> */}
        </ThemeProvider>
      </body>
    </html>
    // </ReactQueryClientProvider>
  );
}
